### ISSUE TITLE
ERROR Could not load truetype file /config/Helvetica.ttf: unknown file format

### ISSUE THREAD

**Issue by Candymirror** [BOlaerts/ESP32-2432s028#1]
Hi, I tried your to install  your code on my device, but ran into the following error:

ERROR Could not load truetype file /config/Helvetica.ttf: unknown file format

Could be I'm missing something in my ESPHome version (freshly installed docker container), but couldn't find any similar issues, except for https://community.home-assistant.io/t/oled-1306-128x64-error-validating/489043 
But that one got no solution. The font is available. I downloaded it from your Github 

Best Regards ,
Ronald

**Comment by BOlaerts** [comment]
Hi Ronald,
Have been away for a while, didn't see this message.
Did you find a solution for your error message?
In my config, I saved the font file in the config/esphome folder, not just in the config folder.
Maybe you can solve the error by moving the font file to that folder.
Best regards,
Bart

**Comment by Candymirror** [comment]
Hi Bart, no problem. I did get arround the problem somehow, but don' t remember how I solved it.Kind Regards,RonaldVerzonden vanaf Outlook voor Android

**Comment by BOlaerts** [comment]
H Ronald,
In my configuration, the font file is not located in the /config/ folder as in the error message, but in the /config/esphome/ folder.
I've put all the files referenced in my ymal in the /config/esphome/ folder.
I think all references start from that folder, so I gues that `file: "fonts/Helvetica.ttf"` would point to config/esphome/fonts/Helvetica.ttf.
